#!/bin/bash

APP_USER_LINUX=#{APP_USER_LINUX}


sudo su - $APP_USER_LINUX << \EOF
    CONF_ROOT=/var/local
    source $CONF_ROOT/config.txt
    echo -e "Clonig git repository from this url:  $GIT_REPO_URL"
    cd /home/$APP_USER
    git clone $GIT_REPO_URL
    cd $GIT_ROOT
    APP_ROOT_DIRECTOR=$(pwd)
    echo "APP_ROOT_DIRECTOR=$APP_ROOT_DIRECTOR" >> "$CONF_ROOT/config.txt"
    cd $APP_ROOT_DIRECTOR
    echo -e "Create Virtualenviroment"
    python3 -m venv .venv
    echo -e "Activate virtualenviroment"
    source .venv/bin/activate
    pip install -r requirements.txt
    pip install -U pip
    python manage.py check
    python manage.py makemigrations
    python manage.py migrate
    echo -e "Configuration Nginx credentials.."
    sed -i -e 's|#{APP_SERVER}|'$APP_SERVER'|g' -e 's|#{APP_ROOT_DIRECTOR}|'$APP_ROOT_DIRECTOR'|g' -e 's|#{APP_NAME}|'$APP_NAME'|g' $CONF_ROOT/tlp/default
    echo -e "Create nginx default server.."
    sudo cp -r $CONF_ROOT/tlp/default /etc/nginx/sites-available/default
    echo -e "Gunicorn file created.."
    sed -i -e 's|#{APP_USER}|'$APP_USER'|g' -e 's|#{APP_ROOT_DIRECTOR}|'$APP_ROOT_DIRECTOR'|g' -e 's|#{APP_NAME}|'$APP_NAME'|g' $CONF_ROOT/tlp/gunicorn.service
    sudo cp -r $CONF_ROOT/tlp/gunicorn.service /etc/systemd/system/
    echo -e "Everything works cool :)"
    sudo cp -r $CONF_ROOT/commands/restart /bin/
    sudo chmod +x /bin/restart
    sudo cp -r $CONF_ROOT/commands/makemigrations /bin/
    sudo chmod +x /bin/makemigrations
    sudo cp -r $CONF_ROOT/commands/shell /bin/
    sudo chmod +x /bin/shell
    sudo systemctl start nginx
    sudo systemctl start gunicorn
    restart
EOF